### ISSUE TITLE
Regisration bug on mobile platform

### ISSUE THREAD

**Issue by cpzaigisz** [rdespoiu/QTitan#67]
Users are unable to complete registration because a popup in the DOB section is preventing users from creating their account. NOT a priority but a bug perhaps preventing the users to see the popup.

**Comment by rdespoiu** [comment]
This can be fixed with a jquery plugin for dates and phone numbers. I'll tackle this

**Comment by rdespoiu** [comment]
https://github.com/rdespoiu/QTitan/pull/72

**Comment by rdespoiu** [comment]
Merged
